(define num-col-row 40)
(define pause-num 1000000)
(define size (floor (/ 750 num-col-row)))
(define obstacle-density 40)
(define high-density 10)
(define stable-density 50)
(load "grid-class.ss")
(load "grid-draw.ss")
(load "grid-make.ss")
(define grid0 (make-grid num-col-row)) 
(draw-obstacles grid0)
(define grid (convert-grid grid0))
(load "grid-new.ss")
(load "grid-ProductionSystem.ss")
(set-goal grid)
(set-start grid)
(draw-start)
(draw-goal)
(draw-robot)
(show canvas)
(search)
